<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Inv.Infra</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BD\" />
    <Folder Include="Database\" />
    <Folder Include="Repositorio\" />
  </ItemGroup>

</Project>
