<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Inv.Dom</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entidades\" />
    <Folder Include="Contratos\" />
    <Folder Include="Repositorio\" />
  </ItemGroup>

</Project>
